name: MidwayFlag
on:
  push:
    branches:
      - main
    paths:
      - CustomSprites/MidwayFlag/**.*
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compress
        run: zip -r MidwayFlag.zip CustomSprites/MidwayFlag

      - name: Create / Edit Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: MidwayFlag
          tag: MidwayFlag
          allowUpdates: true
          replacesArtifacts: true
          bodyFile: CustomSprites/MidwayFlag/README.md
          artifacts: MidwayFlag.zip
          artifactContentType: application/zip
