name: PathController
on:
  push:
    branches:
      - main
    paths:
      - CustomSprites/PathController/**.*
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compress
        run: zip -r PathController.zip CustomSprites/PathController

      - name: Create / Edit Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Path Controller
          tag: PathController
          allowUpdates: true
          replacesArtifacts: true
          bodyFile: Utility/PathController/README.md
          artifacts: PathController.zip
          artifactContentType: application/zip
